services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  app:
    image: colizeum-image
    container_name: colizeum-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/postgres