services:
  database:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  app:
    image: zz1512/app:latest
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: